defaults: &defaults
  facebook_page_url: 'https://www.facebook.com'
  twitter_profile_url: 'https://www.twitter.com'
  owner_url: 'https://evrim.io'
  max_comment_length: 300
  default_meta_title: 'Indie Sumo'
  default_meta_description: ''
  default_meta_image: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults