defaults: &defaults
  facebook_page_url: 'https://www.facebook.com'
  twitter_profile_url: 'https://www.twitter.com'
  owner_url: 'https://evrim.io'
  max_comment_length: 300
  default_meta_title: 'Indie Sumo'
  default_meta_description: ''
  default_meta_image: ''
  default_twitter_share_text: ''
  newsletter_url: 'https://indiesumo.us12.list-manage.com/subscribe/post?u=7d6b207df0db42f6bfcff3322&amp;id=fbb0bb2608'
  app_version: '0.5'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults