defaults: &defaults
  facebook_page_url: 'https://www.facebook.com'
  twitter_profile_url: 'https://www.twitter.com'
  owner_url: 'https://evrim.io'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults