defaults: &defaults
  twitter_profile_url: 'https://twitter.com/evrimfeyyaz'
  owner_url: 'https://evrim.io'
  max_comment_length: 300
  site_name: 'Indie Sumo'
  site_description: 'Top resources for indie developers, bootstrappers and solo entrepreneurs.'
  social_share_image: 'https://s3-us-west-2.amazonaws.com/indie-sumo-production/indie-sumo-social-share.png'
  twitter_share_text: 'Top resources for indie developers, bootstrappers and solo entrepreneurs.'
  google_analytics_tracking_id: 'UA-131220795-1'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults