defaults: &defaults
  facebook_page_url: 'https://www.facebook.com'
  twitter_profile_url: 'https://www.twitter.com'
  owner_url: 'https://evrim.io'
  max_comment_length: 300
  site_name: 'Indie Sumo'
  site_description: 'Top resources for indie developers, bootstrappers and solo entrepreneurs.'
  social_share_image: 'https://s3-us-west-2.amazonaws.com/indie-sumo-production/indie-sumo-social-share.png'
  twitter_share_text: 'Top resources for indie developers, bootstrappers and solo entrepreneurs.'
  newsletter_url: 'https://indiesumo.us12.list-manage.com/subscribe/post?u=7d6b207df0db42f6bfcff3322&amp;id=fbb0bb2608'
  app_version: '0.5'
  google_analytics_tracking_id: 'UA-131220795-1'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults